apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm3-mysql-data-pvc
  namespace: seckou-redhat-dev
  labels:
    app: vm3-db
    role: database-storage
  annotations:
    description: "PVC dédié pour les données MySQL de VM3 - 20Gi"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # Décommenter et adapter si tu as une StorageClass spécifique
  # storageClassName: standard
