apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: tp-openshift-virt
  labels:
    app: mysql-db
  annotations:
    description: "Volume persistant 20Gi pour les données MySQL"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
