apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tp-openshift-virt
  labels:
    app: mysql-db
type: Opaque
stringData:
  # Mot de passe root MySQL
  MYSQL_ROOT_PASSWORD: "RootPass123!"
  # Base de données créée automatiquement
  MYSQL_DATABASE: "appdb"
  # Utilisateur de l'application
  MYSQL_USER: "appuser"
  # Mot de passe de l'utilisateur
  MYSQL_PASSWORD: "AppPass123!"
