apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: seckou-redhat-dev
  labels:
    app: mysql-db
  annotations:
    description: "Service interne MySQL - accessible uniquement depuis le namespace"
spec:
  # ClusterIP = accessible uniquement à l'intérieur du cluster (pas exposé sur Internet)
  type: ClusterIP
  selector:
    app: mysql-db
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
